#!/usr/bin/python3
##
## EPITECH PROJECT, 2023
## 106bombyx
## File description:
## bunny population
##

import sys
import matrixes
import parse
import math
from math import factorial#borrar, es para el facotorial

def print_usage():
    print("USAGE")
    print("\t./108trigo fun a0 a1 a2 ...")
    print("DESCRIPTION")
    print("\tfun\tfunction to be applied, among at least \"EXP\", \"COS\", \"SIN\", \"COSH\"")
    print("\t\tand \"SINH\"")
    print("\tai\tpolinomial denominator defined by its coefficients")

def functions(data):
    size = int(math.sqrt(len(data["matrix"])))
    square_matrix = matrixes.Matrix(size, size, data["matrix"])

    if data["func"] == "EXP":
        result = square_matrix.exp(150)
    if data["func"] == "COS":
        result = square_matrix.cos(150)
    if data["func"] == "SIN":
        result = square.matrix.sin(150)
    if data["func"] == "COSH":
        result = square_matrix.cosh(150)
    if data["func"] == "SINH":
        result = square_matrix.sinh(150)
    print(result)

def main():
    if len(sys.argv) == 2:
        if sys.argv[1] == "-h":
            print_usage()
        else:
            raise Exception("Unrecognized argument")
    else:
        data = parse.parse_data()
        functions(data)

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(e, file=sys.stderr)
        exit(84)
